// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwitcujwsvequtpimsfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3aXRjdWp3c3ZlcXV0cGltc2Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjY3NTgsImV4cCI6MjA2NDYwMjc1OH0.Z9zqHAEEJQzipbKXnLBUJmn24eht7ADM_CKrDp8Io18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);